version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: whatsapp_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: api-lmw
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - "3306:3307"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
